std::shared_ptr<fbf::FunctionIdentifierInternalNode<double, double>> root = std::make_shared<fbf::FunctionIdentifierInternalNode<double, double>>(1.000000003760140421249, sizeof(double), std::vector<size_t>({sizeof(double)}), std::make_tuple(0.000086719555360226157), std::make_tuple(0.000086719555360226157));
std::shared_ptr<fbf::FunctionIdentifierInternalNode<double, double>> node1 = std::make_shared<fbf::FunctionIdentifierInternalNode<double, double>>(-0.713639511824209593626, sizeof(double), std::vector<size_t>({sizeof(double)}), std::make_tuple(295673691282818813663524039661094041600753896804462699604821963055548433518559232.000000000000000000000), std::make_tuple(295673691282818813663524039661094041600753896804462699604821963055548433518559232.000000000000000000000));
std::shared_ptr<fbf::FunctionIdentifierInternalNode<double, double>> node2 = std::make_shared<fbf::FunctionIdentifierInternalNode<double, double>>(-2565.293984181058931426378, sizeof(double), std::vector<size_t>({sizeof(double)}), std::make_tuple(-8.542975583302663267205), std::make_tuple(-8.542975583302663267205));
std::shared_ptr<fbf::FunctionIdentifierInternalNode<double, double>> node3 = std::make_shared<fbf::FunctionIdentifierInternalNode<double, double>>(0.998125929415129564681, sizeof(double), std::vector<size_t>({sizeof(double)}), std::make_tuple(1.509564697152373069499), std::make_tuple(1.509564697152373069499));
std::shared_ptr<fbf::FunctionIdentifierInternalNode<float, float>> node4 = std::make_shared<fbf::FunctionIdentifierInternalNode<float, float>>(2.000000000f, sizeof(float), std::vector<size_t>({sizeof(float)}), std::make_tuple(-2.000000000f), std::make_tuple(-2.000000000f));
std::shared_ptr<fbf::FunctionIdentifierInternalNode<float, float>> node5 = std::make_shared<fbf::FunctionIdentifierInternalNode<float, float>>(-36893488147419103232.000000000f, sizeof(float), std::vector<size_t>({sizeof(float)}), std::make_tuple(36893488147419103232.000000000f), std::make_tuple(36893488147419103232.000000000f));
std::shared_ptr<fbf::FunctionIdentifierInternalNode<long double, long double>> node6 = std::make_shared<fbf::FunctionIdentifierInternalNode<long double, long double>>(-0.358956022975789157403l, sizeof(long double), std::vector<size_t>({sizeof(long double)}), std::make_tuple(4.345239849338304871651l), std::make_tuple(4.345239849338304871651l));
char* buf_0 = (char*) malloc(5);
if(buf_0) { buffers_.push_back(buf_0); std::memcpy(buf_0, "\x8c\xb9\x20\xbf", 4); } else { throw std::runtime_error("malloc failed"); }
char* buf_1 = (char*) malloc(5);
if(buf_1) { buffers_.push_back(buf_1); std::memcpy(buf_1, "\xea\x41\x47\x3f", 4); } else { throw std::runtime_error("malloc failed"); }
char* buf_2 = (char*) malloc(5);
if(buf_2) { buffers_.push_back(buf_2); std::memcpy(buf_2, "\x00\x00\x00\x00", 4); } else { throw std::runtime_error("malloc failed"); }
char* buf_3 = (char*) malloc(5);
if(buf_3) { buffers_.push_back(buf_3); std::memcpy(buf_3, "\x00\x00\x80\x3f", 4); } else { throw std::runtime_error("malloc failed"); }
std::shared_ptr<fbf::FunctionIdentifierInternalNode<void, float, char*, char*>> node7 = std::make_shared<fbf::FunctionIdentifierInternalNode<void, float, char*, char*>>(std::vector<size_t>({sizeof(float),4,4}), std::make_tuple(0E-9f,buf_0,buf_1), std::make_tuple(0E-9f,buf_2,buf_3));
char* buf_4 = (char*) malloc(9);
if(buf_4) { buffers_.push_back(buf_4); std::memcpy(buf_4, "\x0e\x55\x5f\x3a\xaf\x0b\xe1\x3f", 8); } else { throw std::runtime_error("malloc failed"); }
char* buf_5 = (char*) malloc(9);
if(buf_5) { buffers_.push_back(buf_5); std::memcpy(buf_5, "\xb1\x95\x77\xae\x0b\x15\xeb\x3f", 8); } else { throw std::runtime_error("malloc failed"); }
char* buf_6 = (char*) malloc(9);
if(buf_6) { buffers_.push_back(buf_6); std::memcpy(buf_6, "\xb2\x1d\x59\x5e\x1c\x5f\xe6\x3f", 8); } else { throw std::runtime_error("malloc failed"); }
char* buf_7 = (char*) malloc(9);
if(buf_7) { buffers_.push_back(buf_7); std::memcpy(buf_7, "\x2b\x02\x27\xe4\x64\xe1\xe6\x3f", 8); } else { throw std::runtime_error("malloc failed"); }
std::shared_ptr<fbf::FunctionIdentifierInternalNode<void, double, char*, char*>> node8 = std::make_shared<fbf::FunctionIdentifierInternalNode<void, double, char*, char*>>(std::vector<size_t>({sizeof(double),8,8}), std::make_tuple(0.774152296591303690221,buf_4,buf_5), std::make_tuple(0.774152296591303690221,buf_6,buf_7));
std::shared_ptr<fbf::FunctionIdentifierInternalNode<long double, long double>> node9 = std::make_shared<fbf::FunctionIdentifierInternalNode<long double, long double>>(-1593.520680115626873885049l, sizeof(long double), std::vector<size_t>({sizeof(long double)}), std::make_tuple(-8.066848390579680838641l), std::make_tuple(-8.066848390579680838641l));
std::shared_ptr<fbf::FunctionIdentifierInternalNode<float, float>> node10 = std::make_shared<fbf::FunctionIdentifierInternalNode<float, float>>(2.000000000f, sizeof(float), std::vector<size_t>({sizeof(float)}), std::make_tuple(0E-9f), std::make_tuple(0E-9f));
std::shared_ptr<fbf::FunctionIdentifierInternalNode<float, float>> node11 = std::make_shared<fbf::FunctionIdentifierInternalNode<float, float>>(-0E-9f, sizeof(float), std::vector<size_t>({sizeof(float)}), std::make_tuple(-0E-9f), std::make_tuple(-0E-9f));
std::shared_ptr<fbf::FunctionIdentifierInternalNode<long double, long double>> node12 = std::make_shared<fbf::FunctionIdentifierInternalNode<long double, long double>>(2182.630979595891403732821l, sizeof(long double), std::vector<size_t>({sizeof(long double)}), std::make_tuple(-8.381433427555249338070l), std::make_tuple(-8.381433427555249338070l));
char* buf_8 = (char*) malloc(11);
if(buf_8) { buffers_.push_back(buf_8); std::memcpy(buf_8, "\x95\x7e\xce\x65\x08\x2a\x35\xdd\xfe\xbf", 10); } else { throw std::runtime_error("malloc failed"); }
char* buf_9 = (char*) malloc(11);
if(buf_9) { buffers_.push_back(buf_9); std::memcpy(buf_9, "\xb7\xe1\xa0\x20\x00\x70\xda\x80\xfe\xbf", 10); } else { throw std::runtime_error("malloc failed"); }
char* buf_10 = (char*) malloc(11);
if(buf_10) { buffers_.push_back(buf_10); std::memcpy(buf_10, "\xc9\x0e\x99\x2f\x65\x6b\xd7\xfb\xfc\xbf", 10); } else { throw std::runtime_error("malloc failed"); }
char* buf_11 = (char*) malloc(11);
if(buf_11) { buffers_.push_back(buf_11); std::memcpy(buf_11, "\x71\xea\x54\x43\x33\x15\x23\xf8\xfe\x3f", 10); } else { throw std::runtime_error("malloc failed"); }
std::shared_ptr<fbf::FunctionIdentifierInternalNode<void, long double, char*, char*>> node13 = std::make_shared<fbf::FunctionIdentifierInternalNode<void, long double, char*, char*>>(std::vector<size_t>({sizeof(long double),10,10}), std::make_tuple(-6.531673581913484127881l,buf_8,buf_9), std::make_tuple(-6.531673581913484127881l,buf_10,buf_11));
std::shared_ptr<fbf::FunctionIdentifierInternalNode<long double, long double>> node43 = std::make_shared<fbf::FunctionIdentifierInternalNode<long double, long double>>(-0E-21l, sizeof(long double), std::vector<size_t>({sizeof(long double)}), std::make_tuple(-0E-21l), std::make_tuple(-0E-21l));
std::shared_ptr<fbf::FunctionIdentifierNode> sinl_ = std::make_shared<fbf::FunctionIdentifierNode>("sinl", node43);
char* buf_12 = (char*) malloc(11);
if(buf_12) { buffers_.push_back(buf_12); std::memcpy(buf_12, "\xbb\x71\xa8\xfa\xd2\x79\x5d\x88\xfe\x3f", 10); } else { throw std::runtime_error("malloc failed"); }
char* buf_13 = (char*) malloc(11);
if(buf_13) { buffers_.push_back(buf_13); std::memcpy(buf_13, "\x1f\x8b\xad\xbc\x73\x5d\xa8\xd8\xfe\x3f", 10); } else { throw std::runtime_error("malloc failed"); }
char* buf_14 = (char*) malloc(11);
if(buf_14) { buffers_.push_back(buf_14); std::memcpy(buf_14, "\x63\x95\xed\xc8\xf2\xe2\xf8\xb2\xfe\x3f", 10); } else { throw std::runtime_error("malloc failed"); }
char* buf_15 = (char*) malloc(11);
if(buf_15) { buffers_.push_back(buf_15); std::memcpy(buf_15, "\xc3\x56\x11\x38\x21\x27\x0b\xb7\xfe\x3f", 10); } else { throw std::runtime_error("malloc failed"); }
std::shared_ptr<fbf::FunctionIdentifierInternalNode<void, long double, char*, char*>> node44 = std::make_shared<fbf::FunctionIdentifierInternalNode<void, long double, char*, char*>>(std::vector<size_t>({sizeof(long double),10,10}), std::make_tuple(0.774152296591303690221l,buf_12,buf_13), std::make_tuple(0.774152296591303690221l,buf_14,buf_15));
std::shared_ptr<fbf::FunctionIdentifierNode> sincosl_ = std::make_shared<fbf::FunctionIdentifierNode>("sincosl", node44);
std::shared_ptr<fbf::FunctionIdentifierInternalNode<long double, long double>> node45 = std::make_shared<fbf::FunctionIdentifierInternalNode<long double, long double>>(1.161980358317507677768l, sizeof(long double), std::vector<size_t>({sizeof(long double)}), std::make_tuple(0.561759746220724109911l), std::make_tuple(0.561759746220724109911l));
std::shared_ptr<fbf::FunctionIdentifierNode> coshl_ = std::make_shared<fbf::FunctionIdentifierNode>("coshl", node45);
std::shared_ptr<fbf::FunctionIdentifierInternalNode<float, float>> node46 = std::make_shared<fbf::FunctionIdentifierInternalNode<float, float>>(-36893488147419103232.000000000f, sizeof(float), std::vector<size_t>({sizeof(float)}), std::make_tuple(-36893488147419103232.000000000f), std::make_tuple(-36893488147419103232.000000000f));
std::shared_ptr<fbf::FunctionIdentifierNode> sinhf_ = std::make_shared<fbf::FunctionIdentifierNode>("sinhf", node46);
std::shared_ptr<fbf::FunctionIdentifierInternalNode<float, float>> node47 = std::make_shared<fbf::FunctionIdentifierInternalNode<float, float>>(-2.000000000f, sizeof(float), std::vector<size_t>({sizeof(float)}), std::make_tuple(-0E-9f), std::make_tuple(-0E-9f));
std::shared_ptr<fbf::FunctionIdentifierNode> coshf_ = std::make_shared<fbf::FunctionIdentifierNode>("coshf", node47);
std::shared_ptr<fbf::FunctionIdentifierInternalNode<long double, long double>> node48 = std::make_shared<fbf::FunctionIdentifierInternalNode<long double, long double>>(-2182.630750514552801178070l, sizeof(long double), std::vector<size_t>({sizeof(long double)}), std::make_tuple(-8.381433427555249338070l), std::make_tuple(-8.381433427555249338070l));
std::shared_ptr<fbf::FunctionIdentifierNode> sinhl_ = std::make_shared<fbf::FunctionIdentifierNode>("sinhl", node48);
char* buf_16 = (char*) malloc(9);
if(buf_16) { buffers_.push_back(buf_16); std::memcpy(buf_16, "\x00\x00\x00\x00\x00\x00\x00\x00", 8); } else { throw std::runtime_error("malloc failed"); }
char* buf_17 = (char*) malloc(9);
if(buf_17) { buffers_.push_back(buf_17); std::memcpy(buf_17, "\x00\x00\x00\x00\x00\x00\xf0\x3f", 8); } else { throw std::runtime_error("malloc failed"); }
char* buf_18 = (char*) malloc(9);
if(buf_18) { buffers_.push_back(buf_18); std::memcpy(buf_18, "\x00\x00\x00\x00\x00\x00\x00\x80", 8); } else { throw std::runtime_error("malloc failed"); }
char* buf_19 = (char*) malloc(9);
if(buf_19) { buffers_.push_back(buf_19); std::memcpy(buf_19, "\x00\x00\x00\x00\x00\x00\xf0\x3f", 8); } else { throw std::runtime_error("malloc failed"); }
std::shared_ptr<fbf::FunctionIdentifierInternalNode<void, double, char*, char*>> node49 = std::make_shared<fbf::FunctionIdentifierInternalNode<void, double, char*, char*>>(std::vector<size_t>({sizeof(double),8,8}), std::make_tuple(-0E-21,buf_16,buf_17), std::make_tuple(-0E-21,buf_18,buf_19));
std::shared_ptr<fbf::FunctionIdentifierNode> sincos_ = std::make_shared<fbf::FunctionIdentifierNode>("sincos", node49);
char* buf_20 = (char*) malloc(5);
if(buf_20) { buffers_.push_back(buf_20); std::memcpy(buf_20, "\x50\xf0\x6e\xbf", 4); } else { throw std::runtime_error("malloc failed"); }
char* buf_21 = (char*) malloc(5);
if(buf_21) { buffers_.push_back(buf_21); std::memcpy(buf_21, "\x1c\xc9\xb7\xbe", 4); } else { throw std::runtime_error("malloc failed"); }
char* buf_22 = (char*) malloc(5);
if(buf_22) { buffers_.push_back(buf_22); std::memcpy(buf_22, "\x2a\x35\x5d\xbf", 4); } else { throw std::runtime_error("malloc failed"); }
char* buf_23 = (char*) malloc(5);
if(buf_23) { buffers_.push_back(buf_23); std::memcpy(buf_23, "\x71\xda\x00\xbf", 4); } else { throw std::runtime_error("malloc failed"); }
std::shared_ptr<fbf::FunctionIdentifierInternalNode<void, float, char*, char*>> node50 = std::make_shared<fbf::FunctionIdentifierInternalNode<void, float, char*, char*>>(std::vector<size_t>({sizeof(float),4,4}), std::make_tuple(2.000000000f,buf_20,buf_21), std::make_tuple(2.000000000f,buf_22,buf_23));
std::shared_ptr<fbf::FunctionIdentifierNode> sincosf_ = std::make_shared<fbf::FunctionIdentifierNode>("sincosf", node50);
std::shared_ptr<fbf::FunctionIdentifierInternalNode<long double, long double>> node51 = std::make_shared<fbf::FunctionIdentifierInternalNode<long double, long double>>(0.846319046741589642302l, sizeof(long double), std::vector<size_t>({sizeof(long double)}), std::make_tuple(0.561759746220724109911l), std::make_tuple(0.561759746220724109911l));
std::shared_ptr<fbf::FunctionIdentifierNode> cosl_ = std::make_shared<fbf::FunctionIdentifierNode>("cosl", node51);
std::shared_ptr<fbf::FunctionIdentifierInternalNode<float, float>> node52 = std::make_shared<fbf::FunctionIdentifierInternalNode<float, float>>(-2.000000000f, sizeof(float), std::vector<size_t>({sizeof(float)}), std::make_tuple(0E-9f), std::make_tuple(0E-9f));
std::shared_ptr<fbf::FunctionIdentifierNode> cosf_ = std::make_shared<fbf::FunctionIdentifierNode>("cosf", node52);
std::shared_ptr<fbf::FunctionIdentifierInternalNode<float, float>> node53 = std::make_shared<fbf::FunctionIdentifierInternalNode<float, float>>(0E-9f, sizeof(float), std::vector<size_t>({sizeof(float)}), std::make_tuple(1E-9f), std::make_tuple(1E-9f));
std::shared_ptr<fbf::FunctionIdentifierNode> sinf_ = std::make_shared<fbf::FunctionIdentifierNode>("sinf", node53);
std::shared_ptr<fbf::FunctionIdentifierInternalNode<double, double>> node54 = std::make_shared<fbf::FunctionIdentifierInternalNode<double, double>>(0.000001236511513624088, sizeof(double), std::vector<size_t>({sizeof(double)}), std::make_tuple(0.000001236511513624403), std::make_tuple(0.000001236511513624403));
std::shared_ptr<fbf::FunctionIdentifierNode> sin_ = std::make_shared<fbf::FunctionIdentifierNode>("sin", node54);
std::shared_ptr<fbf::FunctionIdentifierInternalNode<double, double>> node55 = std::make_shared<fbf::FunctionIdentifierInternalNode<double, double>>(301961538965222676037768590541983125924114213246788795674463830016.000000000000000000000, sizeof(double), std::vector<size_t>({sizeof(double)}), std::make_tuple(151.466307694029637787025), std::make_tuple(151.466307694029637787025));
std::shared_ptr<fbf::FunctionIdentifierNode> sinh_ = std::make_shared<fbf::FunctionIdentifierNode>("sinh", node55);
std::shared_ptr<fbf::FunctionIdentifierInternalNode<double, double>> node56 = std::make_shared<fbf::FunctionIdentifierInternalNode<double, double>>(0.999999044960486083156, sizeof(double), std::vector<size_t>({sizeof(double)}), std::make_tuple(0.001382056197112939248), std::make_tuple(0.001382056197112939248));
std::shared_ptr<fbf::FunctionIdentifierNode> cos_ = std::make_shared<fbf::FunctionIdentifierNode>("cos", node56);
std::shared_ptr<fbf::FunctionIdentifierInternalNode<double, double>> node57 = std::make_shared<fbf::FunctionIdentifierInternalNode<double, double>>(1.096754224220670703715, sizeof(double), std::vector<size_t>({sizeof(double)}), std::make_tuple(0.436424196261084584858), std::make_tuple(0.436424196261084584858));
std::shared_ptr<fbf::FunctionIdentifierNode> cosh_ = std::make_shared<fbf::FunctionIdentifierNode>("cosh", node57);
root->set_pass_node(cosh_);
node1->set_pass_node(cos_);
node2->set_pass_node(sinh_);
node3->set_pass_node(sin_);
node4->set_pass_node(sinf_);
node5->set_pass_node(cosf_);
node6->set_pass_node(cosl_);
node7->set_pass_node(sincosf_);
node8->set_pass_node(sincos_);
node9->set_pass_node(sinhl_);
node10->set_pass_node(coshf_);
node11->set_pass_node(sinhf_);
node12->set_pass_node(coshl_);
node13->set_pass_node(sincosl_);
root->set_fail_node(node1);
node1->set_fail_node(node2);
node2->set_fail_node(node3);
node3->set_fail_node(node4);
node4->set_fail_node(node5);
node5->set_fail_node(node6);
node6->set_fail_node(node7);
node7->set_fail_node(node8);
node8->set_fail_node(node9);
node9->set_fail_node(node10);
node10->set_fail_node(node11);
node11->set_fail_node(node12);
node12->set_fail_node(node13);
node13->set_fail_node(sinl_);
